version: "3"


services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: product_db
    volumes:
      - webflux_db:/var/lib/postgresql/data
#      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    ports:
      - "5432:5432"

volumes:
  webflux_db:
#  adminer:
#    image: adminer
#    restart: always
#    ports:
#      - "8080:8080"

#    networks:
#      - db_network
#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin
#    restart: always
##    networks:
##      - db_network
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - 80:80
##networks:
##  db_network: {}

